import cv2
import numpy
image = cv2.imread("img_1.png")
#Creating a plain canvas
canvas = numpy.zeros((400,400,3),dtype="uint8")
rectangle = cv2.rectangle(canvas.copy(),(30,30),(370,370),225,-1)
#(canvas,(point1),(point2),(color:BGR),thickness)
circle = cv2.circle(canvas.copy(),(200,200),200,225,-1)
#(canvas,(center points),radius,(color:BGR),thickness)
cv2.imshow("Rectangle",rectangle)
cv2.imshow("Circle",circle)
bitwise_and = cv2.bitwise_and(circle,rectangle)
cv2.imshow("BITWISE_AND",bitwise_and)
bitwise_or = cv2.bitwise_or(rectangle,circle)
cv2.imshow("BITWISE_OR",bitwise_or)
bitwise_xor = cv2.bitwise_xor(rectangle,circle)
cv2.imshow("BITWISE_XOR",bitwise_xor)
bitwise_not = cv2.bitwise_not(circle)
cv2.imshow("BITWISE_NOT",bitwise_not)
canvas_2 = numpy.zeros(image.shape[:2],dtype="uint8")
mask = cv2.circle(canvas_2, (image.shape[1]//2-25,image.shape[0]//2+25),100,255,-1)
#(canvas, (center),radius,color,thickness)
masking_image = cv2.bitwise_and(image,image,mask=mask)
cv2.imshow("Masked Image",masking_image)
circle2 = cv2.circle(canvas_2.copy(),(image.shape[1]//2+45,image.shape[0]//2),100,255,-1)
rectangle2 = cv2.rectangle(canvas_2.copy(),(30,30),(370,370),255,-1)
shape = cv2.bitwise_and(circle2,rectangle2)
masking_image_2 = cv2.bitwise_and(image,image,mask=shape)
cv2.imshow("Masked Image: 2",masking_image_2)
cv2.waitKey(0)