import cv2
import numpy
image = cv2.imread("img_1.png")
cv2.imshow("Original",image)
canvas = numpy.zeros(image.shape[:2],dtype="uint8")
gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow("Gray Scale",gray)
blur = cv2.GaussianBlur(image,(9,9),cv2.BORDER_DEFAULT)     #(9,9) is kernel size (scale of blur) and must be odd numbers
cv2.imshow("Blurred",blur)
outline = cv2.Canny(image,150,150)      #Threshhold values
cv2.imshow("Outline",outline)
#Cropping the image
crop = image[50:200,200:400]
cv2.imshow("Cropped",crop)
rotate = cv2.rotate(image, cv2.ROTATE_90_CLOCKWISE)
cv2.imshow("Rotated Image", rotate)
flip = cv2.flip(image,1)    #0 for horizontal flip & 1 for vertical flip
cv2.imshow("Flipped Image",flip)
res,threshold = cv2.threshold(gray,150,150,cv2.THRESH_BINARY)
cv2.imshow('Threshold Image',threshold)
contours, hierarchies = cv2.findContours(outline,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)
print(f'{len(contours)} Total Contours.')
cv2.drawContours(canvas,contours,-1,(0,255,0),2)
#(canvas,list of contours,number of contours (-1 for all),(color:BGR),thickness)
cv2.imshow("Drawn Contours",canvas)
hsv = cv2.cvtColor(image,cv2.COLOR_BGR2HSV)
cv2.imshow('HSV',hsv)
lab = cv2.cvtColor(image,cv2.COLOR_BGR2LAB)
cv2.imshow('LAB',lab)
rgb = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
cv2.imshow('RGB',rgb)
b,g,r = cv2.split(image)
cv2.imshow("Blue",b)
cv2.imshow("Green",g)
cv2.imshow("Red",r)
merging = cv2.merge([b,g,r])
cv2.imshow('Merged BGR Image',merging)
blue_filter = cv2.merge([b,canvas,canvas])
red_filter = cv2.merge([canvas,canvas,r])
green_filter = cv2.merge([canvas,g,canvas])
cv2.imshow("Blue Filter",blue_filter)
cv2.imshow("Green Filter",green_filter)
cv2.imshow("Red Filter",red_filter)
cv2.waitKey(0)
cv2.destroyAllWindows()