#Create a .py file for the following code
import cv2
# Reading images
img = cv2.imread("img_1.png")
cv2.imshow("Squares",img)        #"Squares" is the title thet will be displayed when image is outputted
cv2.waitKey(0)
# Reading videos
video = cv2.VideoCapture('#3 Asteroids.mp4')
while True:
    isTrue, frame = video.read()
    cv2.imshow("Asteroids",frame)        #"Asteroids" is the title thet will be displayed when image is outputted
    if cv2.waitKey(1) & 0xFF==ord('d'):        #The value entered in the waitKey parentheses determines the speed of the video, smaller the value, greater the speed
        break
video.release()
cv2.destroyAllWindows()      #Pressing any key will close all the Windows that were generated by the code